using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace PillarOfPillar.Event;

public class Builder
{
    public const string DefaultNewLine = "\n";

    public string IndentString { get; set; } = new string(' ', 4);
    public LinkedList<object> HeadLines { get; } = [];
    public LinkedList<object> BodyLines { get; } = [];
    public LinkedList<object> EndLines { get; } = [];

    private class EnterIndent
    {
        public static readonly EnterIndent Instance = new();
        private EnterIndent(){}
    }

    private class ExitIndent
    {
        public static readonly ExitIndent Instance = new();
        private ExitIndent(){}
    }

    public Builder(bool emitComment = true)
    {
        if (emitComment)
        {
            HeadLines.AddFirst("// <auto-generated/>");
        }
    }

    public void EnterNamespace(ISymbol? targetSymbol)
    {
        List<INamespaceSymbol> symbols = [];
        targetSymbol = targetSymbol?.ContainingNamespace;
        while (targetSymbol != null)
        {
            symbols.Add((INamespaceSymbol)targetSymbol);
            targetSymbol = targetSymbol.ContainingNamespace;
        }

        symbols.Reverse();
        foreach (var symbol in symbols)
        {
            if (symbol.IsGlobalNamespace)
            {
                continue;
            }
            PutHeadAndEndWithIndent($"namespace {symbol.Name}\n{{","}");
        }
    }

    public void EnterNamedType(ISymbol? targetSymbol)
    {
        List<INamedTypeSymbol> symbols = [];
        targetSymbol = targetSymbol?.ContainingType;
        while (targetSymbol != null)
        {
            symbols.Add((INamedTypeSymbol)targetSymbol);
            targetSymbol = targetSymbol.ContainingType;
        }

        symbols.Reverse();
        foreach (var symbol in symbols)
        {
            PutHeadAndEndWithIndent($"partial class {symbol.Name}\n{{","}");
        }
    }

    public static string[] SplitIntoLines(string str)
    {
        str = str.Replace("\r\n", "\n").Replace("\r", "\n");
        return str.Split(['\n'], StringSplitOptions.None).Select(s => s.TrimEnd()).ToArray();
    }

    public void PutHeadAndEndWithIndent(string head, string end)
    {
        foreach (var line in SplitIntoLines(head))
        {
            HeadLines.AddLast(line);
        }
        HeadLines.AddLast(EnterIndent.Instance);
        
        foreach (var line in SplitIntoLines(end))
        {
            EndLines.AddFirst(line);
        }
        EndLines.AddFirst(ExitIndent.Instance);
    }

    public void PutBody(string body)
    {
        foreach (var line in SplitIntoLines(body))
        {
            BodyLines.AddLast(line);
        }
    }

    public override string ToString()
    {
        StringBuilder builder = new();
        byte indentLevel = 0;

        foreach (var lines in (LinkedList<object>[])[HeadLines, BodyLines, EndLines])
        {
            foreach (var line in lines)
            {
                if (line is string)
                {
                    Indent();
                    builder.Append(line);
                    builder.Append(DefaultNewLine);
                }
                else if (line is EnterIndent)
                {
                    indentLevel += 1;
                }
                else if (line is ExitIndent)
                {
                    indentLevel -= 1;
                }
                else
                {
                    throw new ArgumentException($"Unknown type to take operation:{line.GetType().FullName}");
                }
            }
        }

        return builder.ToString().Replace("\t", IndentString);
        
        void Indent()
        {
            builder.Append(
                string.Concat(Enumerable.Repeat(IndentString, indentLevel)));
        }
    }
}